//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPANY_MANAGEMENT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMPANYCONTEXTCONN : DbContext
    {
        public COMPANYCONTEXTCONN()
            : base("name=COMPANYCONTEXTCONN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Leader> Leaders { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<CompleteJob> CompleteJobs { get; set; }
        public virtual DbSet<SQLCheck> SQLChecks { get; set; }
        public virtual DbSet<ProcessJob> ProcessJobs { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
    }
}
