//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPANY_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string IDSent { get; set; }
        public string NameSent { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string IDReceive { get; set; }
        public System.DateTime InfoDate { get; set; }
    }
}
