//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPANY_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leader
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string ID_Card { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> Basic_salary { get; set; }
        public string Password { get; set; }
    }
}
