//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPANY_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string ID { get; set; }
        public string Task_Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Task_description { get; set; }
        public string Task_status { get; set; }
        public string Project_ID { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
